version: '3'

services: 
    app:
        build: .
        ports: 
            - 80:80
        volumes:
            - .:/var/www/app

    db:
        image: mysql:8.0
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sistema-treinamento-v2

    composer:
        image: composer:2.0.11
        command: composer install
        volumes: 
            - .:/app
            
    node:
        image: node:14.16.0-alpine
        command: sleep infinity
        volumes: 
            - .:/app
